-- CREATING DATABASE
CREATE DATABASE IF NOT EXISTS `fileconverter`;

-- CREATING USERS TABLE
CREATE TABLE `users` ( `id` INT NOT NULL AUTO_INCREMENT , 
 `username` VARCHAR(100) NOT NULL ,
 `email` VARCHAR(200) NOT NULL ,
 `password` VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`id`)) ENGINE = InnoDB;


-- CREATING FILES TABLE
CREATE TABLE `files` ( `id` INT NOT NULL AUTO_INCREMENT ,
 `userid` INT NOT NULL ,
 `file` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`id`)) ENGINE = InnoDB;

  ALTER TABLE `files` ADD `type` VARCHAR(50) NOT NULL AFTER `file`;